dict = {
'148' : 'A B C up H I K down W',
'93' : '(A B F up D E F) (A B F up DEF Pr Rs H I W) (A up Pr Rs H I W)',
'95' : '(A B D E F down) (A B C up D E F down)',
'98' : '(A B up D E F D E F down) (A B C up D E F D E F down)',
'100' : 'A D E F M N W',
'101' : 'A B C up K M N Ex U W',
'104' : '(F A B C up D E F down U) (A F F M N N N W)',
'105' : '(A B C F up K down) (D E F A C up D E F down Pr Rs)',
'106' : '(A B C up K down) (A B C up K down) (A B up D E down)',
'108' : 'A up D E down Pr Rs Pr Rs',
'113' : 'A C up D E F D E F G K down Pr Rs',
'114' : 'A up D E F D E F down Pr Rs Pr Rs Q W',
'115' : '(A up E F K) (A B C D E F I W)',
'125' : '(D E F A up O) (F A C up H J I K down Pr Rs) L Q Ex U W',
'126' : '(A B C up K down) (D E F A B C F H J I down K T Q W)',
'127' : 'A O F K T Pr Rs Q Ex U W',
'128' : '(A B C up D E F G W) (J A C up F G K W)',
'131' : 'A B C up H I K down W',
'132' : '(A B C up K down G) (A C F up D E F G I down) (A C up D E F G O M N Q Ex U W)',
'133' : '(A C up D E F) (B C up D E H I K down)',
'135' : 'A C F H I K down Pr Rs Pr Rs',
'136' : '(A B D E K F) (A B C K F) (A C H I K down Pr Rs Pr Rs)',
'137' : '(up D E F A C H I down Pr Rs) (A B C F up K F M N M N K down U W)',
'138' : '(A B C up D E F G H I K down Pr Rs Pr Rs) (A C up D E F G) (A C up M N K down)',
'139' : '(up D E F G A B C up H I K J W down) (A C up D E F G O M N Q T X U Q W)',
'140' : 'A B C up D E G F I K down W',
'141' : '(A F UP D E F G F I K down) (A C up F G K U W)',
'143' : '(A C F up H I K down) (A up F H I K down W)',
'144' : 'A M C up F F G M N T W',
'145' : 'A B C up F G K down',
'148' : 'A B C up H I K down W',
'149' : 'A B C up H I K down W',
'150' : '(D E X A B C up K down) (A B C UP H I K down Rs Pr U W)',
'151' : 'A B C up H I K down',
'152' : 'A up H I K down',
'153' : 'A C up F H I X U W down X',
'154' : 'up D E F G T C up F H I K W',
'155' : '(A B C up D E F K down) (A B C up D E F K down) (up Y G W F A B C up G I K U) (A B C up H J I K L Q Ex U W) down X',
'156' : '(A B C up D E F G D E F G K) (A B C up D E F G K down U W) (F A C I G O M N U W W)',
'159' : '(A C up 2 2 K) (W A C up F K Pr Rs) (A B C up K C up K down Pr Rs) (A C F up D E F D E F K F down Pr Rs)',
'161' : '(A B C up H I K down) (A C up F G H I K F) (A C up D E F G I K) (A C up G H I W)',
'162' : 'D E F A H I K A B C up H I K down W',
'163' : 'A F C up G I T W W down',
'164' : '(A C up K down) (A F C up T G W down T I W)',
'166' : '(D E F A up G W) (A G T Q)',
'167' : '(A D E F K T U W) (W A B C up G) (A B C M N W down)'
}
